### ISSUE TITLE
npm or pnpm?

### ISSUE THREAD

**Issue by kerns** [brandtam/sveltekit-sanity-starter#2]
Looks like a nice project, look forward to playing with it. But is there a reason you jump between npm and pnpm in the setup instructions?

**Comment by brandtam** [comment]
@kerns  thanks for checking it out. There's a reason but not a logical one. It's just that I haven't worked on the Readme at all. I added a couple of notes as I went but it's mostly just the basic sveltekit Readme. I use pnpm and love it. But you can use whatever package manager you like. 

I'll update the Readme next. Let my know if you have any questions on setup. Cheers

**Comment by kerns** [comment]
Thanks, I will... just had been under the impression you had to pick on and stick with it.

**Comment by brandtam** [comment]
That is correct. You should use one package manager and stick with it. I'm using 'pnpm' while the old Readme was using 'npm'.

I've updated the Readme now with better instructions on how to use this template.
